# -*- coding: utf-8 -*-
"""480_OOP_7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ANO3pHF8DfzHqQhNnMjJHN0y4h6Tp0e6
"""

class Flight:

    max_passengers = 3

    def __init__(self, number):
        self.number = number
        self.passengers = []
        self.waiting_list = []

    def add_passenger(self, passenger):
        if len(self.passengers) >= Flight.max_passengers:
            self.waiting_list.append(passenger)
        else:
            self.passengers.append(passenger)

# Write your code below:

my_flight = Flight('ISM480')
my_flight.add_passenger ('Bo')
my_flight.add_passenger ('Jalyn')

#access passanger list
print(f'Here are in the passengers in flight {my_flight.number}:')
for p in my_flight.passengers:
  print(p)